import AuthLayout from "@/components/auth/auth-layout"
import LoginForm from "@/components/auth/login-form"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login | AJAR",
    description: "Generated by create next app",
};

export default function LoginPage() {
  return <AuthLayout FormComponent={<LoginForm />} />
}
