import ReportDropdown from "@/components/reports-dropdown";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Reports | AJAR",
    description: "Generated by create next app",
};

export default async function ReportLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <div className="relative">
                    <div className="absolute right-3 sm:right-10 top-6 lg:top-7">
                        <ReportDropdown />
                    </div>
                    {children}
                </div>
            </body>
        </html>
    );
}
