"use client"
import AuthLayout from "@/components/auth/auth-layout"
import RegisterForm from "@/components/auth/register-form"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Register | AJAR",
    description: "Generated by create next app",
};


export default function RegisterPage() {
  return <AuthLayout FormComponent={<RegisterForm />} />
}
