import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
    title: "Home | AJAR",
    description: "Generated by create next app",
};

export default async function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                {children}
            </body>
        </html>
    );
}
