import VehicleCard from '@/components/categories/vehicle-card'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Vehicles | AJAR",
  description: "Generated by create next app",
};

export default function VehiclesPage() {
  return (
    <VehicleCard />
  );
}

