import RoomCard from '@/components/categories/room-card'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Rooms | AJAR",
  description: "Generated by create next app",
};

const RoomsPage = () => {
  return (
    <RoomCard />
  )
}

export default RoomsPage
