import AppartmentCard from "@/components/categories/appartment-card"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Appartments | AJAR",
  description: "Generated by create next app",
};

const AppartmentsPage = () => {
  return (
    <AppartmentCard />
  )
}

export default AppartmentsPage
